# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MALD' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MALD
    pod 'Socket.IO-Client-Swift', '~> 16.1.0'
    pod 'IQKeyboardManagerSwift'


end
